micronaut:
  application:
    name: base
    max: 50
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
          - http://localhost:4200
          allowedMethods:
          - POST
          - PUT
          - GET
          - OPTIONS
  router:
    static-resources:
      default:
        enabled: true   
        mapping: "/**"  
        paths: "classpath:static" 
jackson:
  bean-introspection-module: true
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://172.17.0.1:5432/base`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    packages-to-scan:
      - 'com.up.domain.model' 
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        bytecode:
          provider: none
